package com.github.tharthar2.saf2021.core.init;

import com.oblivioussp.spartanweaponry.api.SpartanWeaponryAPI;
import com.oblivioussp.spartanweaponry.api.WeaponMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import com.github.tharthar2.saf2021.SaF2021;
import net.minecraftforge.registries.IForgeRegistry;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS,
            SaF2021.modid);
    public static Item FDS1;
    public static Item FDS2;
    public static Item FDS3;
    public static Item FDS4;
    public static Item FDS5;
    public static Item FDS6;
    public static Item FDS7;
    public static Item FDS8;
    public static Item FDS9;
    public static Item FDS10;
    public static Item FDS11;
    public static Item FDS12;
    public static Item FDS13;
    public static Item FDS14;
    public static Item FDS15;
    public static Item FDS16;
    public static Item FDS17;
    public static Item FDS18;
    public static Item FDS19;
    public static Item FDS20;
    public static Item FDS21;

    public static Item IDS1;
    public static Item IDS2;
    public static Item IDS3;
    public static Item IDS4;
    public static Item IDS5;
    public static Item IDS6;
    public static Item IDS7;
    public static Item IDS8;
    public static Item IDS9;
    public static Item IDS10;
    public static Item IDS11;
    public static Item IDS12;
    public static Item IDS13;
    public static Item IDS14;
    public static Item IDS15;
    public static Item IDS16;
    public static Item IDS17;
    public static Item IDS18;
    public static Item IDS19;
    public static Item IDS20;
    public static Item IDS21;

    public static Item LDS1;
    public static Item LDS2;
    public static Item LDS3;
    public static Item LDS4;
    public static Item LDS5;
    public static Item LDS6;
    public static Item LDS7;
    public static Item LDS8;
    public static Item LDS9;
    public static Item LDS10;
    public static Item LDS11;
    public static Item LDS12;
    public static Item LDS13;
    public static Item LDS14;
    public static Item LDS15;
    public static Item LDS16;
    public static Item LDS17;
    public static Item LDS18;
    public static Item LDS19;
    public static Item LDS20;
    public static Item LDS21;

    @SubscribeEvent
    public static void onItemRegisterEvent(RegistryEvent.Register<Item> ev)
    {
        IForgeRegistry<Item> reg = ev.getRegistry();
        WeaponMaterial FDS = materials.materialFDS;
        WeaponMaterial IDS = materials.materialIDS;
        WeaponMaterial LDS = materials.materialLDS;

        ItemGroup g = ItemGroup.COMBAT;
        FDS1=SpartanWeaponryAPI.createBattleaxe(FDS,g);
        FDS2=SpartanWeaponryAPI.createBattleHammer(FDS,g);
        FDS3=SpartanWeaponryAPI.createBoomerang(FDS,g);
        FDS4=SpartanWeaponryAPI.createDagger(FDS,g);
        FDS5=SpartanWeaponryAPI.createFlangedMace(FDS,g);
        FDS6=SpartanWeaponryAPI.createGlaive(FDS,g);
        FDS7=SpartanWeaponryAPI.createGreatsword(FDS,g);
        FDS8=SpartanWeaponryAPI.createHalberd(FDS,g);
        FDS8=SpartanWeaponryAPI.createHeavyCrossbow(FDS,g);
        FDS9=SpartanWeaponryAPI.createJavelin(FDS,g);
        FDS10=SpartanWeaponryAPI.createKatana(FDS,g);
        FDS11=SpartanWeaponryAPI.createLance(FDS,g);
        FDS12=SpartanWeaponryAPI.createLongbow(FDS,g);
        FDS13=SpartanWeaponryAPI.createLongsword(FDS,g);
        FDS14=SpartanWeaponryAPI.createPike(FDS,g);
        FDS15=SpartanWeaponryAPI.createQuarterstaff(FDS,g);
        FDS16=SpartanWeaponryAPI.createRapier(FDS,g);
        FDS17=SpartanWeaponryAPI.createSaber(FDS,g);
        FDS18=SpartanWeaponryAPI.createSpear(FDS,g);
        FDS19=SpartanWeaponryAPI.createThrowingKnife(FDS,g);
        FDS20=SpartanWeaponryAPI.createTomahawk(FDS,g);
        FDS21=SpartanWeaponryAPI.createWarhammer(FDS,g);

        IDS1=SpartanWeaponryAPI.createBattleaxe(IDS,g);
        IDS2=SpartanWeaponryAPI.createBattleHammer(IDS,g);
        IDS3=SpartanWeaponryAPI.createBoomerang(IDS,g);
        IDS4=SpartanWeaponryAPI.createDagger(IDS,g);
        IDS5=SpartanWeaponryAPI.createFlangedMace(IDS,g);
        IDS6=SpartanWeaponryAPI.createGlaive(IDS,g);
        IDS7=SpartanWeaponryAPI.createGreatsword(IDS,g);
        IDS8=SpartanWeaponryAPI.createHalberd(IDS,g);
        IDS8=SpartanWeaponryAPI.createHeavyCrossbow(IDS,g);
        IDS9=SpartanWeaponryAPI.createJavelin(IDS,g);
        IDS10=SpartanWeaponryAPI.createKatana(IDS,g);
        IDS11=SpartanWeaponryAPI.createLance(IDS,g);
        IDS12=SpartanWeaponryAPI.createLongbow(IDS,g);
        IDS13=SpartanWeaponryAPI.createLongsword(IDS,g);
        IDS14=SpartanWeaponryAPI.createPike(IDS,g);
        IDS15=SpartanWeaponryAPI.createQuarterstaff(IDS,g);
        IDS16=SpartanWeaponryAPI.createRapier(IDS,g);
        IDS17=SpartanWeaponryAPI.createSaber(IDS,g);
        IDS18=SpartanWeaponryAPI.createSpear(IDS,g);
        IDS19=SpartanWeaponryAPI.createThrowingKnife(IDS,g);
        IDS20=SpartanWeaponryAPI.createTomahawk(IDS,g);
        IDS21=SpartanWeaponryAPI.createWarhammer(IDS,g);

        LDS1=SpartanWeaponryAPI.createBattleaxe(LDS,g);
        LDS2=SpartanWeaponryAPI.createBattleHammer(LDS,g);
        LDS3=SpartanWeaponryAPI.createBoomerang(LDS,g);
        LDS4=SpartanWeaponryAPI.createDagger(LDS,g);
        LDS5=SpartanWeaponryAPI.createFlangedMace(LDS,g);
        LDS6=SpartanWeaponryAPI.createGlaive(LDS,g);
        LDS7=SpartanWeaponryAPI.createGreatsword(LDS,g);
        LDS8=SpartanWeaponryAPI.createHalberd(LDS,g);
        LDS8=SpartanWeaponryAPI.createHeavyCrossbow(LDS,g);
        LDS9=SpartanWeaponryAPI.createJavelin(LDS,g);
        LDS10=SpartanWeaponryAPI.createKatana(LDS,g);
        LDS11=SpartanWeaponryAPI.createLance(LDS,g);
        LDS12=SpartanWeaponryAPI.createLongbow(LDS,g);
        LDS13=SpartanWeaponryAPI.createLongsword(LDS,g);
        LDS14=SpartanWeaponryAPI.createPike(LDS,g);
        LDS15=SpartanWeaponryAPI.createQuarterstaff(LDS,g);
        LDS16=SpartanWeaponryAPI.createRapier(LDS,g);
        LDS17=SpartanWeaponryAPI.createSaber(LDS,g);
        LDS18=SpartanWeaponryAPI.createSpear(LDS,g);
        LDS19=SpartanWeaponryAPI.createThrowingKnife(LDS,g);
        LDS20=SpartanWeaponryAPI.createTomahawk(LDS,g);
        LDS21=SpartanWeaponryAPI.createWarhammer(LDS,g);

        reg.register(FDS1);
        reg.register(FDS2);
        reg.register(FDS3);
        reg.register(FDS4);
        reg.register(FDS5);
        reg.register(FDS6);
        reg.register(FDS7);
        reg.register(FDS8);
        reg.register(FDS9);
        reg.register(FDS10);
        reg.register(FDS12);
        reg.register(FDS13);
        reg.register(FDS14);
        reg.register(FDS15);
        reg.register(FDS16);
        reg.register(FDS17);
        reg.register(FDS18);
        reg.register(FDS19);
        reg.register(FDS20);
        reg.register(FDS21);

        reg.register(IDS1);
        reg.register(IDS2);
        reg.register(IDS3);
        reg.register(IDS4);
        reg.register(IDS5);
        reg.register(IDS6);
        reg.register(IDS7);
        reg.register(IDS8);
        reg.register(IDS9);
        reg.register(IDS10);
        reg.register(IDS12);
        reg.register(IDS13);
        reg.register(IDS14);
        reg.register(IDS15);
        reg.register(IDS16);
        reg.register(IDS17);
        reg.register(IDS18);
        reg.register(IDS19);
        reg.register(IDS20);
        reg.register(IDS21);

        reg.register(LDS1);
        reg.register(LDS2);
        reg.register(LDS3);
        reg.register(LDS4);
        reg.register(LDS5);
        reg.register(LDS6);
        reg.register(LDS7);
        reg.register(LDS8);
        reg.register(LDS9);
        reg.register(LDS10);
        reg.register(LDS12);
        reg.register(LDS13);
        reg.register(LDS14);
        reg.register(LDS15);
        reg.register(LDS16);
        reg.register(LDS17);
        reg.register(LDS18);
        reg.register(LDS19);
        reg.register(LDS20);
        reg.register(LDS21);
    }
}
