package com.github.tharthar2.saf2021.core.init;

import com.github.alexthe666.iceandfire.enums.EnumTroll;
import com.oblivioussp.spartanweaponry.api.SpartanWeaponryAPI;
import com.oblivioussp.spartanweaponry.api.WeaponMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import com.github.tharthar2.saf2021.SaF2021;
import net.minecraftforge.registries.IForgeRegistry;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS,
            SaF2021.modid);
    public static final RegistryObject<Item> WB_handle = ITEMS.register("witherbone_handle",()-> new Item(new Item.Properties().group(ItemGroup.MATERIALS)));
    public static final RegistryObject<Item> WB_pole = ITEMS.register("witherbone_pole",()-> new Item(new Item.Properties().group(ItemGroup.MATERIALS)));

    public static Item FDS1;
    public static Item FDS2;
    public static Item FDS3;
    public static Item FDS4;
    public static Item FDS5;
    public static Item FDS6;
    public static Item FDS7;
    public static Item FDS8;
    public static Item FDS9;
    public static Item FDS10;
    public static Item FDS11;
    public static Item FDS12;
    public static Item FDS13;
    public static Item FDS14;
    public static Item FDS15;
    public static Item FDS16;
    public static Item FDS17;
    public static Item FDS18;
    public static Item FDS19;
    public static Item FDS20;
    public static Item FDS21;

    public static Item IDS1;
    public static Item IDS2;
    public static Item IDS3;
    public static Item IDS4;
    public static Item IDS5;
    public static Item IDS6;
    public static Item IDS7;
    public static Item IDS8;
    public static Item IDS9;
    public static Item IDS10;
    public static Item IDS11;
    public static Item IDS12;
    public static Item IDS13;
    public static Item IDS14;
    public static Item IDS15;
    public static Item IDS16;
    public static Item IDS17;
    public static Item IDS18;
    public static Item IDS19;
    public static Item IDS20;
    public static Item IDS21;

    public static Item LDS1;
    public static Item LDS2;
    public static Item LDS3;
    public static Item LDS4;
    public static Item LDS5;
    public static Item LDS6;
    public static Item LDS7;
    public static Item LDS8;
    public static Item LDS9;
    public static Item LDS10;
    public static Item LDS11;
    public static Item LDS12;
    public static Item LDS13;
    public static Item LDS14;
    public static Item LDS15;
    public static Item LDS16;
    public static Item LDS17;
    public static Item LDS18;
    public static Item LDS19;
    public static Item LDS20;
    public static Item LDS21;

    public static Item FDB1;
    public static Item FDB2;
    public static Item FDB3;
    public static Item FDB4;
    public static Item FDB5;
    public static Item FDB6;
    public static Item FDB7;
    public static Item FDB8;
    public static Item FDB9;
    public static Item FDB10;
    public static Item FDB11;
    public static Item FDB12;
    public static Item FDB13;
    public static Item FDB14;
    public static Item FDB15;
    public static Item FDB16;
    public static Item FDB17;
    public static Item FDB18;
    public static Item FDB19;
    public static Item FDB20;
    public static Item FDB21;

    public static Item IDB1;
    public static Item IDB2;
    public static Item IDB3;
    public static Item IDB4;
    public static Item IDB5;
    public static Item IDB6;
    public static Item IDB7;
    public static Item IDB8;
    public static Item IDB9;
    public static Item IDB10;
    public static Item IDB11;
    public static Item IDB12;
    public static Item IDB13;
    public static Item IDB14;
    public static Item IDB15;
    public static Item IDB16;
    public static Item IDB17;
    public static Item IDB18;
    public static Item IDB19;
    public static Item IDB20;
    public static Item IDB21;

    public static Item LDB1;
    public static Item LDB2;
    public static Item LDB3;
    public static Item LDB4;
    public static Item LDB5;
    public static Item LDB6;
    public static Item LDB7;
    public static Item LDB8;
    public static Item LDB9;
    public static Item LDB10;
    public static Item LDB11;
    public static Item LDB12;
    public static Item LDB13;
    public static Item LDB14;
    public static Item LDB15;
    public static Item LDB16;
    public static Item LDB17;
    public static Item LDB18;
    public static Item LDB19;
    public static Item LDB20;
    public static Item LDB21;

    public static Item DB1;
    public static Item DB2;
    public static Item DB3;
    public static Item DB4;
    public static Item DB5;
    public static Item DB6;
    public static Item DB7;
    public static Item DB8;
    public static Item DB9;
    public static Item DB10;
    public static Item DB11;
    public static Item DB12;
    public static Item DB13;
    public static Item DB14;
    public static Item DB15;
    public static Item DB16;
    public static Item DB17;
    public static Item DB18;
    public static Item DB19;
    public static Item DB20;
    public static Item DB21;
    @SubscribeEvent
    public static void onItemRegisterEvent(RegistryEvent.Register<Item> ev)
    {
        IForgeRegistry<Item> reg = ev.getRegistry();
        WeaponMaterial FDS = materials.materialFDS;
        WeaponMaterial IDS = materials.materialIDS;
        WeaponMaterial LDS = materials.materialLDS;
        WeaponMaterial FDB = materials.materialFDB;
        WeaponMaterial IDB = materials.materialIDB;
        WeaponMaterial LDB = materials.materialLDB;
        WeaponMaterial DB = materials.materialDB;

        ItemGroup g = ItemGroup.COMBAT;
        FDS1=SpartanWeaponryAPI.createBattleaxe(FDS,g);
        FDS2=SpartanWeaponryAPI.createBattleHammer(FDS,g);
        FDS3=SpartanWeaponryAPI.createBoomerang(FDS,g);
        FDS4=SpartanWeaponryAPI.createDagger(FDS,g);
        FDS5=SpartanWeaponryAPI.createFlangedMace(FDS,g);
        FDS6=SpartanWeaponryAPI.createGlaive(FDS,g);
        FDS7=SpartanWeaponryAPI.createGreatsword(FDS,g);
        FDS8=SpartanWeaponryAPI.createHalberd(FDS,g);
        FDS8=SpartanWeaponryAPI.createHeavyCrossbow(FDS,g);
        FDS9=SpartanWeaponryAPI.createJavelin(FDS,g);
        FDS10=SpartanWeaponryAPI.createKatana(FDS,g);
        FDS11=SpartanWeaponryAPI.createLance(FDS,g);
        FDS12=SpartanWeaponryAPI.createLongbow(FDS,g);
        FDS13=SpartanWeaponryAPI.createLongsword(FDS,g);
        FDS14=SpartanWeaponryAPI.createPike(FDS,g);
        FDS15=SpartanWeaponryAPI.createQuarterstaff(FDS,g);
        FDS16=SpartanWeaponryAPI.createRapier(FDS,g);
        FDS17=SpartanWeaponryAPI.createSaber(FDS,g);
        FDS18=SpartanWeaponryAPI.createSpear(FDS,g);
        FDS19=SpartanWeaponryAPI.createThrowingKnife(FDS,g);
        FDS20=SpartanWeaponryAPI.createTomahawk(FDS,g);
        FDS21=SpartanWeaponryAPI.createWarhammer(FDS,g);

        IDS1=SpartanWeaponryAPI.createBattleaxe(IDS,g);
        IDS2=SpartanWeaponryAPI.createBattleHammer(IDS,g);
        IDS3=SpartanWeaponryAPI.createBoomerang(IDS,g);
        IDS4=SpartanWeaponryAPI.createDagger(IDS,g);
        IDS5=SpartanWeaponryAPI.createFlangedMace(IDS,g);
        IDS6=SpartanWeaponryAPI.createGlaive(IDS,g);
        IDS7=SpartanWeaponryAPI.createGreatsword(IDS,g);
        IDS8=SpartanWeaponryAPI.createHalberd(IDS,g);
        IDS8=SpartanWeaponryAPI.createHeavyCrossbow(IDS,g);
        IDS9=SpartanWeaponryAPI.createJavelin(IDS,g);
        IDS10=SpartanWeaponryAPI.createKatana(IDS,g);
        IDS11=SpartanWeaponryAPI.createLance(IDS,g);
        IDS12=SpartanWeaponryAPI.createLongbow(IDS,g);
        IDS13=SpartanWeaponryAPI.createLongsword(IDS,g);
        IDS14=SpartanWeaponryAPI.createPike(IDS,g);
        IDS15=SpartanWeaponryAPI.createQuarterstaff(IDS,g);
        IDS16=SpartanWeaponryAPI.createRapier(IDS,g);
        IDS17=SpartanWeaponryAPI.createSaber(IDS,g);
        IDS18=SpartanWeaponryAPI.createSpear(IDS,g);
        IDS19=SpartanWeaponryAPI.createThrowingKnife(IDS,g);
        IDS20=SpartanWeaponryAPI.createTomahawk(IDS,g);
        IDS21=SpartanWeaponryAPI.createWarhammer(IDS,g);

        LDS1=SpartanWeaponryAPI.createBattleaxe(LDS,g);
        LDS2=SpartanWeaponryAPI.createBattleHammer(LDS,g);
        LDS3=SpartanWeaponryAPI.createBoomerang(LDS,g);
        LDS4=SpartanWeaponryAPI.createDagger(LDS,g);
        LDS5=SpartanWeaponryAPI.createFlangedMace(LDS,g);
        LDS6=SpartanWeaponryAPI.createGlaive(LDS,g);
        LDS7=SpartanWeaponryAPI.createGreatsword(LDS,g);
        LDS8=SpartanWeaponryAPI.createHalberd(LDS,g);
        LDS8=SpartanWeaponryAPI.createHeavyCrossbow(LDS,g);
        LDS9=SpartanWeaponryAPI.createJavelin(LDS,g);
        LDS10=SpartanWeaponryAPI.createKatana(LDS,g);
        LDS11=SpartanWeaponryAPI.createLance(LDS,g);
        LDS12=SpartanWeaponryAPI.createLongbow(LDS,g);
        LDS13=SpartanWeaponryAPI.createLongsword(LDS,g);
        LDS14=SpartanWeaponryAPI.createPike(LDS,g);
        LDS15=SpartanWeaponryAPI.createQuarterstaff(LDS,g);
        LDS16=SpartanWeaponryAPI.createRapier(LDS,g);
        LDS17=SpartanWeaponryAPI.createSaber(LDS,g);
        LDS18=SpartanWeaponryAPI.createSpear(LDS,g);
        LDS19=SpartanWeaponryAPI.createThrowingKnife(LDS,g);
        LDS20=SpartanWeaponryAPI.createTomahawk(LDS,g);
        LDS21=SpartanWeaponryAPI.createWarhammer(LDS,g);

        FDB1=SpartanWeaponryAPI.createBattleaxe(FDB,g);
        FDB2=SpartanWeaponryAPI.createBattleHammer(FDB,g);
        FDB3=SpartanWeaponryAPI.createBoomerang(FDB,g);
        FDB4=SpartanWeaponryAPI.createDagger(FDB,g);
        FDB5=SpartanWeaponryAPI.createFlangedMace(FDB,g);
        FDB6=SpartanWeaponryAPI.createGlaive(FDB,g);
        FDB7=SpartanWeaponryAPI.createGreatsword(FDB,g);
        FDB8=SpartanWeaponryAPI.createHalberd(FDB,g);
        FDB8=SpartanWeaponryAPI.createHeavyCrossbow(FDB,g);
        FDB9=SpartanWeaponryAPI.createJavelin(FDB,g);
        FDB10=SpartanWeaponryAPI.createKatana(FDB,g);
        FDB11=SpartanWeaponryAPI.createLance(FDB,g);
        FDB12=SpartanWeaponryAPI.createLongbow(FDB,g);
        FDB13=SpartanWeaponryAPI.createLongsword(FDB,g);
        FDB14=SpartanWeaponryAPI.createPike(FDB,g);
        FDB15=SpartanWeaponryAPI.createQuarterstaff(FDB,g);
        FDB16=SpartanWeaponryAPI.createRapier(FDB,g);
        FDB17=SpartanWeaponryAPI.createSaber(FDB,g);
        FDB18=SpartanWeaponryAPI.createSpear(FDB,g);
        FDB19=SpartanWeaponryAPI.createThrowingKnife(FDB,g);
        FDB20=SpartanWeaponryAPI.createTomahawk(FDB,g);
        FDB21=SpartanWeaponryAPI.createWarhammer(FDB,g);

        IDB1=SpartanWeaponryAPI.createBattleaxe(IDB,g);
        IDB2=SpartanWeaponryAPI.createBattleHammer(IDB,g);
        IDB3=SpartanWeaponryAPI.createBoomerang(IDB,g);
        IDB4=SpartanWeaponryAPI.createDagger(IDB,g);
        IDB5=SpartanWeaponryAPI.createFlangedMace(IDB,g);
        IDB6=SpartanWeaponryAPI.createGlaive(IDB,g);
        IDB7=SpartanWeaponryAPI.createGreatsword(IDB,g);
        IDB8=SpartanWeaponryAPI.createHalberd(IDB,g);
        IDB8=SpartanWeaponryAPI.createHeavyCrossbow(IDB,g);
        IDB9=SpartanWeaponryAPI.createJavelin(IDB,g);
        IDB10=SpartanWeaponryAPI.createKatana(IDB,g);
        IDB11=SpartanWeaponryAPI.createLance(IDB,g);
        IDB12=SpartanWeaponryAPI.createLongbow(IDB,g);
        IDB13=SpartanWeaponryAPI.createLongsword(IDB,g);
        IDB14=SpartanWeaponryAPI.createPike(IDB,g);
        IDB15=SpartanWeaponryAPI.createQuarterstaff(IDB,g);
        IDB16=SpartanWeaponryAPI.createRapier(IDB,g);
        IDB17=SpartanWeaponryAPI.createSaber(IDB,g);
        IDB18=SpartanWeaponryAPI.createSpear(IDB,g);
        IDB19=SpartanWeaponryAPI.createThrowingKnife(IDB,g);
        IDB20=SpartanWeaponryAPI.createTomahawk(IDB,g);
        IDB21=SpartanWeaponryAPI.createWarhammer(IDB,g);

        LDB1=SpartanWeaponryAPI.createBattleaxe(LDB,g);
        LDB2=SpartanWeaponryAPI.createBattleHammer(LDB,g);
        LDB3=SpartanWeaponryAPI.createBoomerang(LDB,g);
        LDB4=SpartanWeaponryAPI.createDagger(LDB,g);
        LDB5=SpartanWeaponryAPI.createFlangedMace(LDB,g);
        LDB6=SpartanWeaponryAPI.createGlaive(LDB,g);
        LDB7=SpartanWeaponryAPI.createGreatsword(LDB,g);
        LDB8=SpartanWeaponryAPI.createHalberd(LDB,g);
        LDB8=SpartanWeaponryAPI.createHeavyCrossbow(LDB,g);
        LDB9=SpartanWeaponryAPI.createJavelin(LDB,g);
        LDB10=SpartanWeaponryAPI.createKatana(LDB,g);
        LDB11=SpartanWeaponryAPI.createLance(LDB,g);
        LDB12=SpartanWeaponryAPI.createLongbow(LDB,g);
        LDB13=SpartanWeaponryAPI.createLongsword(LDB,g);
        LDB14=SpartanWeaponryAPI.createPike(LDB,g);
        LDB15=SpartanWeaponryAPI.createQuarterstaff(LDB,g);
        LDB16=SpartanWeaponryAPI.createRapier(LDB,g);
        LDB17=SpartanWeaponryAPI.createSaber(LDB,g);
        LDB18=SpartanWeaponryAPI.createSpear(LDB,g);
        LDB19=SpartanWeaponryAPI.createThrowingKnife(LDB,g);
        LDB20=SpartanWeaponryAPI.createTomahawk(LDB,g);
        LDB21=SpartanWeaponryAPI.createWarhammer(LDB,g);

        DB1=SpartanWeaponryAPI.createBattleaxe(DB,g);
        DB2=SpartanWeaponryAPI.createBattleHammer(DB,g);
        DB3=SpartanWeaponryAPI.createBoomerang(DB,g);
        DB4=SpartanWeaponryAPI.createDagger(DB,g);
        DB5=SpartanWeaponryAPI.createFlangedMace(DB,g);
        DB6=SpartanWeaponryAPI.createGlaive(DB,g);
        DB7=SpartanWeaponryAPI.createGreatsword(DB,g);
        DB8=SpartanWeaponryAPI.createHalberd(DB,g);
        DB8=SpartanWeaponryAPI.createHeavyCrossbow(DB,g);
        DB9=SpartanWeaponryAPI.createJavelin(DB,g);
        DB10=SpartanWeaponryAPI.createKatana(DB,g);
        DB11=SpartanWeaponryAPI.createLance(DB,g);
        DB12=SpartanWeaponryAPI.createLongbow(DB,g);
        DB13=SpartanWeaponryAPI.createLongsword(DB,g);
        DB14=SpartanWeaponryAPI.createPike(DB,g);
        DB15=SpartanWeaponryAPI.createQuarterstaff(DB,g);
        DB16=SpartanWeaponryAPI.createRapier(DB,g);
        DB17=SpartanWeaponryAPI.createSaber(DB,g);
        DB18=SpartanWeaponryAPI.createSpear(DB,g);
        DB19=SpartanWeaponryAPI.createThrowingKnife(DB,g);
        DB20=SpartanWeaponryAPI.createTomahawk(DB,g);
        DB21=SpartanWeaponryAPI.createWarhammer(DB,g);

        reg.register(FDS1);
        reg.register(FDS2);
        reg.register(FDS3);
        reg.register(FDS4);
        reg.register(FDS5);
        reg.register(FDS6);
        reg.register(FDS7);
        //reg.register(FDS8);
        reg.register(FDS9);
        reg.register(FDS10);
        reg.register(FDS12);
        reg.register(FDS13);
        reg.register(FDS14);
        reg.register(FDS15);
        reg.register(FDS16);
        reg.register(FDS17);
        reg.register(FDS18);
        reg.register(FDS19);
        //reg.register(FDS20);
        reg.register(FDS21);

        reg.register(IDS1);
        reg.register(IDS2);
        reg.register(IDS3);
        reg.register(IDS4);
        reg.register(IDS5);
        reg.register(IDS6);
        reg.register(IDS7);
        //reg.register(IDS8);
        reg.register(IDS9);
        reg.register(IDS10);
        reg.register(IDS12);
        reg.register(IDS13);
        reg.register(IDS14);
        reg.register(IDS15);
        reg.register(IDS16);
        reg.register(IDS17);
        reg.register(IDS18);
        reg.register(IDS19);
        //reg.register(IDS20);
        reg.register(IDS21);

        reg.register(LDS1);
        reg.register(LDS2);
        reg.register(LDS3);
        reg.register(LDS4);
        reg.register(LDS5);
        reg.register(LDS6);
        reg.register(LDS7);
        //reg.register(LDS8);
        reg.register(LDS9);
        reg.register(LDS10);
        reg.register(LDS12);
        reg.register(LDS13);
        reg.register(LDS14);
        reg.register(LDS15);
        reg.register(LDS16);
        reg.register(LDS17);
        reg.register(LDS18);
        reg.register(LDS19);
        //reg.register(LDS20);
        reg.register(LDS21);

        reg.register(FDB1);
        reg.register(FDB2);
        reg.register(FDB3);
        reg.register(FDB4);
        reg.register(FDB5);
        reg.register(FDB6);
        reg.register(FDB7);
        //reg.register(FDB8);
        reg.register(FDB9);
        reg.register(FDB10);
        reg.register(FDB12);
        reg.register(FDB13);
        reg.register(FDB14);
        reg.register(FDB15);
        reg.register(FDB16);
        reg.register(FDB17);
        reg.register(FDB18);
        reg.register(FDB19);
        //reg.register(FDB20);
        reg.register(FDB21);

        reg.register(IDB1);
        reg.register(IDB2);
        reg.register(IDB3);
        reg.register(IDB4);
        reg.register(IDB5);
        reg.register(IDB6);
        reg.register(IDB7);
        //reg.register(IDB8);
        reg.register(IDB9);
        reg.register(IDB10);
        reg.register(IDB12);
        reg.register(IDB13);
        reg.register(IDB14);
        reg.register(IDB15);
        reg.register(IDB16);
        reg.register(IDB17);
        reg.register(IDB18);
        reg.register(IDB19);
        //reg.register(IDB20);
        reg.register(IDB21);

        reg.register(LDB1);
        reg.register(LDB2);
        reg.register(LDB3);
        reg.register(LDB4);
        reg.register(LDB5);
        reg.register(LDB6);
        reg.register(LDB7);
        //reg.register(LDB8);
        reg.register(LDB9);
        reg.register(LDB10);
        reg.register(LDB12);
        reg.register(LDB13);
        reg.register(LDB14);
        reg.register(LDB15);
        reg.register(LDB16);
        reg.register(LDB17);
        reg.register(LDB18);
        reg.register(LDB19);
        //reg.register(LDB20);
        reg.register(LDB21);

        reg.register(DB1);
        reg.register(DB2);
        reg.register(DB3);
        reg.register(DB4);
        reg.register(DB5);
        reg.register(DB6);
        reg.register(DB7);
        //reg.register(DB8);
        reg.register(DB9);
        reg.register(DB10);
        reg.register(DB12);
        reg.register(DB13);
        reg.register(DB14);
        reg.register(DB15);
        reg.register(DB16);
        reg.register(DB17);
        reg.register(DB18);
        reg.register(DB19);
        //reg.register(DB20);
        reg.register(DB21);
    }
}
